spring:
  # redis配置
  redis:
    host: 172.28.128.3
    port: 6379
    database: 5
    # jedis连接池配置
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
#    password: 123456
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 1000

